---
title: "Material on GSA and the SAFE toolbox"
output: html_document

---

<br> 

## Global Sensitivity Analysis (GSA) material

 - <a href="Noacco_GSA_SAFE_intro_25_09_2020.pdf#" class="download" title="Download GSA and SAFE intro">Brief introductory presentation on GSA and the SAFE toolbox</a>		

 - [A review of available methods and workflow for Sensitivity Analysis (open access paper)](https://www.sciencedirect.com/science/article/pii/S1364815216300287)
 
 - [Practical guide through the critical choices needed for Global Sensitivity Analysis (open access paper)](https://doi.org/10.1016/j.mex.2019.09.033)
 
 - [A systematic review to support scientific advancement and to inform policy-making in earth system modelling (open access paper)](https://research-information.bris.ac.uk/ws/portalfiles/portal/189945689/Wagener_Pianosi_ESR_11.pdf)

 - <a href="GSA_Case_Studies.pdf#" class="download" title="Download examples of GSA-SAFE as PDF">Brief description of a range of GSA/SAFE applications</a>	
 
 - [Paper on the issue of handling epistemic uncertainty due to climate change in landslide hazard modelling (open access paper)](https://www.nat-hazards-earth-syst-sci.net/17/225/2017/nhess-17-225-2017-discussion.html)
 
 - [Paper on a GSA/SAFE application to a flood inundation model (open access paper)](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1002/2015WR018198)
 

<br>  
 
## Sensitivity Analysis For Everybody (SAFE) toolbox
 
 - [Website to download SAFE](https://www.safetoolbox.info/)

- [Introductory paper to SAFE (open access paper)](https://www.sciencedirect.com/science/article/pii/S1364815215001188)

- <a href="workflow_PAWN_ishigami_homma_to_share.html#" class="download" title="PAWN_IshigamiHomma">Workflow to guide in the application of the PAWN GSA method using the SAFE toolbox and to interpret the results</a>


<br> <br>

## Introductory video to Sensitivity Analysis

```{r video, echo=FALSE, warning=FALSE}
library("vembedr")
embed_url("https://vimeo.com/467774754")
```






